import { NextRequest, NextResponse } from "next/server";
import { buildSystemPrompt, ExperienceLevel, Domain, OutputMode } from "@/lib/personas";

const GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";

export async function POST(req: NextRequest) {
  try {
    const { apiKey, prompt, level, domain, mode, targetTool } = await req.json();

    if (!apiKey) {
      return NextResponse.json({ error: "Gemini API Key is required" }, { status: 400 });
    }
    if (!prompt) {
      return NextResponse.json({ error: "Prompt text is required" }, { status: 400 });
    }

    const systemPrompt = buildSystemPrompt(
      level as ExperienceLevel,
      domain as Domain,
      mode as OutputMode,
      targetTool as any
    );

    const requestBody = {
      system_instruction: { parts: { text: systemPrompt } },
      contents: [{ parts: [{ text: `USER RAW INPUT:\n${prompt}` }] }],
      generationConfig: { temperature: 0.7, maxOutputTokens: 8192 },
    };

    const response = await fetch(`${GEMINI_API_URL}?key=${apiKey}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const err = await response.json();
      return NextResponse.json(
        { error: err?.error?.message || `API Error ${response.status}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    const result = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!result) {
      return NextResponse.json({ error: "No response generated by AI." }, { status: 500 });
    }

    return NextResponse.json({ result: result.trim() });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || "Internal server error" }, { status: 500 });
  }
}
